# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  database: mitap_develop
  default: &default
  adapter: mysql2
  encoding: utf8
  username:
  password:
  host: localhost
  port: 3306
  timeout: 5000


